version: 2

before:
  hooks:
    - go mod tidy
    - make

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w'
      - '-X github.com/serenibyss/nhprtracker/internal.Version={{ .Env.version }}'
      - '-X github.com/serenibyss/nhprtracker/internal.Branch={{ .Env.branch }}'
      - '-X github.com/serenibyss/nhprtracker/internal.Commit={{ .Env.commit }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

release:
  skip_upload: true

nfpms:
  - package_name: nhprtracker
    vendor: Serenibyss
    homepage: github.com/serenibyss/nhprtracker
    maintainer: Serenibyss <serenibyss@gmail.com>
    description: CLI to gather PRs merged to a main/master branch and not a release branch
    formats:
      - deb
      - rpm
    # Name template result:
    # nhprtracker-1.0.0.aarch64.rpm
    # nhprtracker-1.0.0.x86_64.rpm
    # nhprtracker_1.0.0_arm64.deb
    # nhprtracker_1.0.0_amd64.deb
    file_name_template: >-
      {{- if eq .ConventionalExtension ".deb" }}
        {{- .PackageName }}_{{ .Env.version }}_{{ .Arch }}
      {{- else if eq .ConventionalExtension ".rpm" }}
        {{- .PackageName }}-{{ .Env.version }}.
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "arm64" }}aarch64
        {{- else }}{{ .Arch }}{{ end }}
      {{- end }}
      {{- .ConventionalExtension }}

archives:
  - format: tar.gz
    files:
      - README.md
    name_template: >-
      {{ .ProjectName }}-{{ .Env.version }}-{{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
snapshot:
  name_template: "{{ .Env.version }}-snapshot"
changelog:
  sort: asc